spring:
  h2:
    console:
      enabled: true          # 开启 H2 控制台
      path: /h2      # 控制台路径：http://localhost:8080/h2

mybatis-flex:
  datasource:
    ds1:
      type: druid
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:./.data/demodb
      username: sa
      password: