spring:
  ai:
    mcp:
      client:
        name: shiyu-ai-mcp
        request-timeout: 300s
        sse:
          connections:
            weather-mcp-server:
              url: http://127.0.0.1:9003
