shiyu:
  # 名称
  name: "shiyu-agent"
  # 版本
  version: ${revision}
  config:
    path:
      json: E:\Dev\IdeaProjects\shiyu-ai\config.json
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    # 应用的访问路径
    context-path: /
  # undertow 配置
  undertow:
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256

springdoc:
  api-docs:
    enabled: false               # 是否启用 API 文档
    path: /v3/api-docs         # OpenAPI JSON 文档访问路径，默认 /v3/api-docs
  #逗号分割
  packages-to-scan: com.shiyu.ai.agent.controller
  group-configs:
    - group: 'default'
      paths-to-match:
        - '/**'
      packages-to-scan:
        - com.shiyu.ai.agent.controller
  swagger-ui:
    path: /swagger-ui/index.html      # Swagger UI 访问路径，默认 /swagger-ui/index.html
    display-request-duration: true  # 显示请求耗时
    operations-sorter: alpha     # 按字母排序接口
    tags-sorter: alpha           # 按标签排序
    default-model-rendering: example # 默认显示 model 示例

# Spring配置
spring:
  application:
    name: ${shiyu.name}
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: @profiles.active@
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
  ai:
    openai:
      api-key: sk-loqlkwllyfseuttatsjqsndtwvaqzklexdwekwmjuhyuyavu
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3
    mcp:
      client:
        name: shiyu-ai-mcp
        request-timeout: 300s
        sse:
          connections:
            weather-mcp-server:
              url: http://127.0.0.1:9000
