shiyu:
  # 名称
  name: "shiyu-chat"
  # 版本
  version: ${revision}
  config:
    path:
      json: E:\Dev\IdeaProjects\shiyu-ai\config.json

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9001

springdoc:
  api-docs:
    enabled: false               # 是否启用 API 文档
    path: /v3/api-docs         # OpenAPI JSON 文档访问路径，默认 /v3/api-docs
  #逗号分割
  packages-to-scan: com.shiyu.ai.chat.controller
  group-configs:
    - group: 'default'
      paths-to-match:
        - '/**'
      packages-to-scan:
        - com.shiyu.ai.chat.controller
  swagger-ui:
    path: /swagger-ui/index.html      # Swagger UI 访问路径，默认 /swagger-ui/index.html
    display-request-duration: true  # 显示请求耗时
    operations-sorter: alpha     # 按字母排序接口
    tags-sorter: alpha           # 按标签排序
    default-model-rendering: example # 默认显示 model 示例

# Spring配置
spring:
  application:
    name: ${shiyu.name}
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: @profiles.active@
    group:
      dev: ai
    default: @profiles.active@

liteflow:
  #规则文件路径
  rule-source: liteflow/chain/chain.json