spring:
  ai:
    # 没有作用，是接入多个兼容openai api的平台
    openai:
      api-key: sk-loqlkwllyfseuttatsjqsndtwvaqzklexdwekwmjuhyuyavu
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3