shiyu:
  # 名称
  name: "shiyu-chat"
  # 版本
  version: ${revision}

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9001
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    # 应用的访问路径
    context-path: /

springdoc:
  api-docs:
    enabled: false               # 是否启用 API 文档
    path: /v3/api-docs         # OpenAPI JSON 文档访问路径，默认 /v3/api-docs
  #逗号分割
  packages-to-scan: com.shiyu.ai.demo.controller
  group-configs:
    - group: 'default'
      paths-to-match:
        - '/**'
      packages-to-scan:
        - com.shiyu.ai.demo.controller
  swagger-ui:
    path: /swagger-ui/index.html      # Swagger UI 访问路径，默认 /swagger-ui/index.html
    display-request-duration: true  # 显示请求耗时
    operations-sorter: alpha     # 按字母排序接口
    tags-sorter: alpha           # 按标签排序
    default-model-rendering: example # 默认显示 model 示例

# Spring配置
spring:
  application:
    name: ${shiyu.name}
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: @profiles.active@
    group:
      dev: h2
    default: @profiles.active@
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
liteflow:
  #规则文件路径
  rule-source: liteflow/chain/chain.json